fix: cli compilation (#2)
* chore: installs tsx

* refactor: use `tsx` instead of `ts-node`

* chore: disable `wrapCommand` for now as it breaks

TypeError: Cannot set property handler of #<Object> which has only a getter

* chore: uninstalls ts-node

* chore: mv `typescript` to `devDependencies`

It is no longer needed at runtime as we use `tsx`