fix: bin paths (#5)
* fix: sets `buildPath` to `dist`

* fix: sets bin to correct path

* fix: use workspace dependency resolution

* docs: use jsdoc instead of comments

* fix: cli compilation (#2)

* chore: installs tsx

* refactor: use `tsx` instead of `ts-node`

* chore: disable `wrapCommand` for now as it breaks

TypeError: Cannot set property handler of #<Object> which has only a getter

* chore: uninstalls ts-node

* chore: mv `typescript` to `devDependencies`

It is no longer needed at runtime as we use `tsx`

* fix: enables type declaration files on build (#4)

* fix: sets `buildPath` to `dist`

* fix: enables type declaration files on build

* fix: use workspace dependency resolution

* docs: use jsdoc instead of comments

* fix: cli compilation (#2)

* chore: installs tsx

* refactor: use `tsx` instead of `ts-node`

* chore: disable `wrapCommand` for now as it breaks

TypeError: Cannot set property handler of #<Object> which has only a getter

* chore: uninstalls ts-node

* chore: mv `typescript` to `devDependencies`

It is no longer needed at runtime as we use `tsx`